version: '3.4'

services:
  web:
    image: tanatis/library
    build: .
    ports:
      - "8000:8000"
    env_file:
      - envs/.env
    platform: linux/amd64
    command: gunicorn --bind=0.0.0.0:8000 library_app.wsgi:application
    links:
      - postgres

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres-user
      POSTGRES_DB: library_app_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data

#  nginx:
#    image: nginx
#    ports:
#      - "80:80"
#      - "443:443"
#    depends_on:
#      - web
#    volumes:
#      - /tmp/library_app/static:/home/app/web/staticfiles
#      - /tmp/library_app/media:/home/app/web/media
#      - ./nginx/conf.d:/etc/nginx/conf.d
#      - ./nginx/logs:/var/log/nginx
#      - ./certbot/www:/var/www/certbot/:ro
#      - ./certbot/conf/:/etc/nginx/ssl/:ro
#    links:
#      - web