# Generated by Django 4.2.3 on 2023-07-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0002_alter_borrow_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrow',
            options={'ordering': ['return_date']},
        ),
    ]
