# Generated by Django 4.2.3 on 2023-07-15 16:53

import django.core.validators
from django.db import migrations, models
import library_app.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_appuser_username_alter_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(error_messages='User with this email already exists.', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='username',
            field=models.CharField(error_messages='This username is already taken', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(3), library_app.core.validators.username_validator]),
        ),
    ]
