# Generated by Django 4.2.3 on 2023-08-11 12:21

from django.db import migrations, models
import library_app.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birth_year',
            field=models.PositiveIntegerField(default=1, validators=[library_app.core.validators.author_birth_death_year_validator]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='death_year',
            field=models.IntegerField(blank=True, null=True, validators=[library_app.core.validators.author_birth_death_year_validator]),
        ),
        migrations.AddField(
            model_name='author',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='author-images', validators=[library_app.core.validators.max_image_size_validator]),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=50, validators=[library_app.core.validators.author_name_validator]),
        ),
    ]
