# Generated by Django 4.2.3 on 2023-07-10 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_author_birth_year_author_death_year_author_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1800, 'Must be above 1800'), django.core.validators.MaxValueValidator(2020, 'Must be below 2020')]),
        ),
        migrations.AlterField(
            model_name='author',
            name='death_year',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800, 'Must be above 1800'), django.core.validators.MaxValueValidator(2020, 'Must be below 2020')]),
        ),
    ]
