# Generated by Django 4.2.3 on 2023-07-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_alter_author_birth_year_alter_author_death_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='death_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
