# Generated by Django 4.2.3 on 2023-07-10 14:10

from django.db import migrations, models
import library_app.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_alter_author_death_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_year',
            field=models.PositiveIntegerField(validators=[library_app.core.validators.author_birth_death_year_validator]),
        ),
        migrations.AlterField(
            model_name='author',
            name='death_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[library_app.core.validators.author_birth_death_year_validator]),
        ),
    ]
