# Generated by Django 4.2.3 on 2023-07-07 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('genre', models.CharField(choices=[('romance', 'Romance'), ('mystery', 'Mystery'), ('thriller', 'Thriller'), ('science', 'Science'), ('fiction', 'Fiction'), ('fantasy', 'Fantasy'), ('horror', 'Horror'), ('historical', 'Historical'), ('adventure', 'Adventure'), ('children', 'Children'), ('drama', 'Drama'), ('comedy', 'Comedy'), ('poetry', 'Poetry'), ('classic', 'Classic'), ('literature', 'Literature')], max_length=10)),
                ('availability', models.IntegerField(default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.author')),
            ],
        ),
    ]
