# Generated by Django 4.2.3 on 2023-07-10 12:56

from django.db import migrations, models
import django.utils.timezone
import library_app.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='1', upload_to='', validators=[library_app.core.validators.max_image_size_validator]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='number_of_pages',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
