# Generated by Django 4.2.3 on 2023-07-10 13:12

from django.db import migrations, models
import library_app.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_cover_book_number_of_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(upload_to='book-covers', validators=[library_app.core.validators.max_image_size_validator]),
        ),
    ]
